#! /bin/csh -f

#=======================================================================
# CVS $Id: Makeprep,v 1.1 1998/08/21 22:54:04 kauff Exp $
# CVS $Source: /fs/cgd/home0/kauff/pac/CVS.REPOS/pac3/Makeprep,v $
# CVS $Name: pac3_e $
#=======================================================================
# prepares an object code list and a source code dependancy list
# to be included into the Makefile
#-----------------------------------------------------------------------

ls *.[fF]               >! Source   # list of source code in cwd
echo '.'                >! Filepath # Makedep's file search path
echo 'makeobj haha'
perl Makeobj          Source >! Objects  # Makefile's object code list
echo 'makedep haha'
perl Makedep Filepath Source >! Depends  # Makefile's dependency list
echo 'makeprep done haha'
